---
title: "Ramme for patientsikkerhed"
author: "Introduktionslæge, PHD Magnus Glindvad Ahlström"
date: "31 jul 2018"
output:
  ioslides_presentation: 
    logo: C:/Kurser/Developing_Data_Products2/Slides/STPS_SMALL.png
    css: C:/Kurser/Developing_Data_Products2/Slides/styles.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##Overordnede rammer

- **Vision: <br> <span style="color:red">Et sikkert og lærende sundhedsvæsen</span>**
- **Mission: <br> <span style="color:red">Vi arbejder for, at det er trygt (sikkert) at være patient</span>**

## Udfordringer?

1. Hvad forstår vi patientsikkerhed?
2. Hvad forstår vi ved risiko?
3. Hvordan identificeres temaer og områder?
4. Hvordan identificeres behandlingssteder?
5. Hvem skal der gås reaktivt tilsyn på?
6. Hvilke data skal vi bruge og hvordan?

##Centrale begreber

**Sikkerhed: <br> <span style="color:red">Fraværet af beskadigelse</span>**

**Patientsikkerhed: <br> <span style="color:red">Fraværet af beskadigelse mens du er patient</span>**

##Klassisk epidemilogi




## Løsning på udfordringer?

1. Hvad forstår vi patientsikkerhed?
Det er ikke sikkert vi er enige i at det er en god forståelse af patientsikkerhed
Giver en god opdeling af begreberne?
Uden fejl sker der ikke skade pga. fejl
Allerede eksisterende frameworks for patientsikkerhed rummes i denne model
2. Hvad forstår vi ved risiko
3. Hvordan identificeres temaer og områder
Risikofaktorerne for at fejl opstår
Risici efter en fejl er opstået
Giver klarhed over hvor ”vi befinder os” på den akse 
4. Hvordan identificeres behandlingssteder
Hvis vi har data
5. Hvilke data skal vi bruge og hvordan
Et grundlag for diskussion
6. Balance mellem kontrol og læring
Et grundlag for diskussion


